
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package amuse;

/** CUP generated class containing symbol constants. */
public class Amuse {
  /* terminals */
  public static final int elseclause = 4;
  public static final int parIzq = 12;
  public static final int number = 10;
  public static final int MainProgram = 21;
  public static final int parDer = 13;
  public static final int cbOpen = 15;
  public static final int booleano = 8;
  public static final int opAnd = 19;
  public static final int ifstart = 2;
  public static final int elseif = 5;
  public static final int EOF = 0;
  public static final int endif = 6;
  public static final int id = 9;
  public static final int opRel = 16;
  public static final int opNot = 20;
  public static final int ifthen = 3;
  public static final int error = 1;
  public static final int voidType = 11;
  public static final int opArit = 17;
  public static final int cbClose = 14;
  public static final int begin = 7;
  public static final int opOr = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ifstart",
  "ifthen",
  "elseclause",
  "elseif",
  "endif",
  "begin",
  "booleano",
  "id",
  "number",
  "voidType",
  "parIzq",
  "parDer",
  "cbClose",
  "cbOpen",
  "opRel",
  "opArit",
  "opOr",
  "opAnd",
  "opNot",
  "MainProgram"
  };
}

