
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package amuse;

/** CUP generated class containing symbol constants. */
public class Amuse {
  /* terminals */
  public static final int character = 28;
  public static final int elseclause = 4;
  public static final int number = 18;
  public static final int parIzq = 10;
  public static final int MainProgram = 7;
  public static final int parDer = 11;
  public static final int end = 9;
  public static final int coma = 15;
  public static final int cbOpen = 12;
  public static final int booleano = 16;
  public static final int num = 27;
  public static final int opAnd = 23;
  public static final int ifstart = 2;
  public static final int bool = 26;
  public static final int elseif = 5;
  public static final int opAsig = 25;
  public static final int EOF = 0;
  public static final int endif = 6;
  public static final int opRel = 20;
  public static final int id = 17;
  public static final int opNot = 24;
  public static final int ifthen = 3;
  public static final int voidType = 19;
  public static final int error = 1;
  public static final int opArit = 21;
  public static final int whilestart = 29;
  public static final int cbClose = 13;
  public static final int begin = 8;
  public static final int opOr = 22;
  public static final int ret = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ifstart",
  "ifthen",
  "elseclause",
  "elseif",
  "endif",
  "MainProgram",
  "begin",
  "end",
  "parIzq",
  "parDer",
  "cbOpen",
  "cbClose",
  "ret",
  "coma",
  "booleano",
  "id",
  "number",
  "voidType",
  "opRel",
  "opArit",
  "opOr",
  "opAnd",
  "opNot",
  "opAsig",
  "bool",
  "num",
  "character",
  "whilestart"
  };
}

