
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package amuse;

/** CUP generated class containing symbol constants. */
public class Amuse {
  /* terminals */
  public static final int opRel = 22;
  public static final int bool = 32;
  public static final int parDer = 10;
  public static final int MainProgram = 7;
  public static final int whilestart = 35;
  public static final int opNot = 25;
  public static final int opAnd = 24;
  public static final int coma = 14;
  public static final int voidType = 20;
  public static final int opDiv = 30;
  public static final int opMult = 29;
  public static final int closeBrk = 17;
  public static final int end = 8;
  public static final int cbClose = 12;
  public static final int ifstart = 2;
  public static final int writestart = 38;
  public static final int elseclause = 4;
  public static final int options = 41;
  public static final int breaks = 40;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int pcoma = 15;
  public static final int opSuma = 27;
  public static final int colon = 42;
  public static final int forstart = 36;
  public static final int endif = 6;
  public static final int parIzq = 9;
  public static final int ret = 13;
  public static final int opOr = 23;
  public static final int cbOpen = 11;
  public static final int openBrk = 16;
  public static final int comment = 43;
  public static final int opAsig = 26;
  public static final int id = 19;
  public static final int charval = 34;
  public static final int selectstart = 39;
  public static final int ifthen = 3;
  public static final int elseif = 5;
  public static final int booleano = 18;
  public static final int contador = 37;
  public static final int character = 21;
  public static final int opResta = 28;
  public static final int num = 33;
  public static final int number = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ifstart",
  "ifthen",
  "elseclause",
  "elseif",
  "endif",
  "MainProgram",
  "end",
  "parIzq",
  "parDer",
  "cbOpen",
  "cbClose",
  "ret",
  "coma",
  "pcoma",
  "openBrk",
  "closeBrk",
  "booleano",
  "id",
  "voidType",
  "character",
  "opRel",
  "opOr",
  "opAnd",
  "opNot",
  "opAsig",
  "opSuma",
  "opResta",
  "opMult",
  "opDiv",
  "number",
  "bool",
  "num",
  "charval",
  "whilestart",
  "forstart",
  "contador",
  "writestart",
  "selectstart",
  "breaks",
  "options",
  "colon",
  "comment"
  };
}

