/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amuse;

/**
 *
 * @author juany
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        lb_titulo1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        btn_fileChooser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_codigoInt = new javax.swing.JButton();
        lb_titulo = new javax.swing.JLabel();
        btn_compilar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lb_codigoFinal = new javax.swing.JLabel();
        lb_archivo = new javax.swing.JLabel();
        lb_background = new javax.swing.JLabel();

        jFrame1.setMinimumSize(new java.awt.Dimension(600, 600));
        jFrame1.setPreferredSize(new java.awt.Dimension(600, 600));

        lb_titulo1.setBackground(new java.awt.Color(153, 153, 153));
        lb_titulo1.setFont(new java.awt.Font("Rockwell", 1, 60)); // NOI18N
        lb_titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo1.setText("Codigo Intermedio");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setPreferredSize(new java.awt.Dimension(1300, 800));
        setSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_fileChooser.setBackground(new java.awt.Color(153, 153, 153));
        btn_fileChooser.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        btn_fileChooser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/saa.png"))); // NOI18N
        btn_fileChooser.setText("Ingresar Archivo");
        btn_fileChooser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fileChooserActionPerformed(evt);
            }
        });
        getContentPane().add(btn_fileChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 300, 80));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 420, 550));

        btn_codigoInt.setBackground(new java.awt.Color(153, 153, 153));
        btn_codigoInt.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        btn_codigoInt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/dss.png"))); // NOI18N
        btn_codigoInt.setText("Codigo Intermedio");
        btn_codigoInt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btn_codigoInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 300, 80));

        lb_titulo.setFont(new java.awt.Font("Rockwell", 1, 60)); // NOI18N
        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo.setText("AMUSE");
        getContentPane().add(lb_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 870, 70));

        btn_compilar.setBackground(new java.awt.Color(153, 153, 153));
        btn_compilar.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        btn_compilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/556.png"))); // NOI18N
        btn_compilar.setText("Compilar");
        btn_compilar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btn_compilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 300, 80));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 420, 550));

        lb_codigoFinal.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        lb_codigoFinal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_codigoFinal.setText("codigo final");
        getContentPane().add(lb_codigoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 670, 200, -1));

        lb_archivo.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        lb_archivo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_archivo.setText("Archivo");
        getContentPane().add(lb_archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, 200, -1));

        lb_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Cadet-Grey-Solid-Color-Background-Wallpaper-5120x2880.png"))); // NOI18N
        getContentPane().add(lb_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fileChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_codigoInt;
    private javax.swing.JButton btn_compilar;
    private javax.swing.JButton btn_fileChooser;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel lb_archivo;
    private javax.swing.JLabel lb_background;
    private javax.swing.JLabel lb_codigoFinal;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JLabel lb_titulo1;
    // End of variables declaration//GEN-END:variables
}
